//=============================================================================
// ReplacePictureName.js
// ----------------------------------------------------------------------------
// <利用規約>
//  利用はRPGツクールMV/RPGMakerMVの正規ユーザーに限られます。
//  商用、非商用、ゲームの内容を問わず利用可能です。
//  ゲームへの利用の際、報告や出典元の記載等は必須ではありません。
//  二次配布や転載は禁止します。
//  ソースコードURL、ダウンロードURLへの直接リンクも禁止します。
//  不具合対応以外のサポートやリクエストは受け付けておりません。
//  スクリプト利用により生じたいかなる問題においても、一切責任を負いかねます。
// ----------------------------------------------------------------------------
//  Ver1.00  2016/01/24  初版
//=============================================================================

/*:
 * @plugindesc 画像、音声、動画読み込み時、指定された名前を任意の名前に置き換えて読み込むようにします。
 * @author こま
 *
 * @help 使い方については、プラグインに同梱されているドキュメントをご参照ください。
 */

(function(){
    var ReplaceNameList = { 
        img:{ 
            "img/animations/Ice4＋.png":"img/animations/Material0001.png", 
            "img/animations/ここの素材について.txt":"img/animations/Material0002.txt", 
            "img/battlecommands/Com_Ｃ技能.png":"img/battlecommands/Material0003.png", 
            "img/battlecommands/Com_Ｉ技能.png":"img/battlecommands/Material0004.png", 
            "img/battlecommands/Com_Ｓ・ドール.png":"img/battlecommands/Material0005.png", 
            "img/battlecommands/Com_Ｓ技能.png":"img/battlecommands/Material0006.png", 
            "img/battlecommands/Com_Λ・アクション.png":"img/battlecommands/Material0007.png", 
            "img/battlecommands/Com_道具.png":"img/battlecommands/Material0008.png", 
            "img/battlecommands/Com_スキル.png":"img/battlecommands/Material0009.png", 
            "img/battlecommands/Com_パッシブ.png":"img/battlecommands/Material0010.png", 
            "img/battlecommands/Com_攻撃.png":"img/battlecommands/Material0011.png", 
            "img/battlecommands/Com_防御.png":"img/battlecommands/Material0012.png", 
            "img/characters/!光源関係1.png":"img/characters/Material0013.png", 
            "img/characters/$透明君.png":"img/characters/Material0014.png", 
            "img/characters/$毒スライムデカ.png":"img/characters/Material0015.png", 
            "img/characters/アークロッド学園.png":"img/characters/Material0016.png", 
            "img/parallaxes/!草原下地-free.png":"img/parallaxes/Material0017.png", 
            "img/parallaxes/!地下闘技場.png":"img/parallaxes/Material0018.png", 
            "img/parallaxes/CGドール乗り砂漠背景.png":"img/parallaxes/Material0019.png", 
            "img/pictures/BCG_絶頂ゲージ00.png":"img/pictures/Material0020.png", 
            "img/pictures/BCG_絶頂ゲージ01.png":"img/pictures/Material0021.png", 
            "img/pictures/BCG_絶頂ゲージ02.png":"img/pictures/Material0022.png", 
            "img/pictures/BCG_絶頂ゲージ03.png":"img/pictures/Material0023.png", 
            "img/pictures/BCG_絶頂ゲージ04.png":"img/pictures/Material0024.png", 
            "img/pictures/BCG_絶頂ゲージ05.png":"img/pictures/Material0025.png", 
            "img/pictures/ECG ダッシュ黒→→.png":"img/pictures/Material0026.png", 
            "img/pictures/ECG ダッシュ黒←←.png":"img/pictures/Material0027.png", 
            "img/pictures/ECG射精エフェクト_0001.png":"img/pictures/Material0028.png", 
            "img/pictures/ECG射精エフェクト_0002.png":"img/pictures/Material0029.png", 
            "img/pictures/ECG射精エフェクト_0003.png":"img/pictures/Material0030.png", 
            "img/pictures/ECG射精エフェクト_0004.png":"img/pictures/Material0031.png", 
            "img/pictures/ECG射精エフェクト_0005.png":"img/pictures/Material0032.png", 
            "img/pictures/ECG射精エフェクト_0006.png":"img/pictures/Material0033.png", 
            "img/pictures/ECG射精エフェクト_0007.png":"img/pictures/Material0034.png", 
            "img/pictures/ECG射精エフェクト2_0001.png":"img/pictures/Material0035.png", 
            "img/pictures/ECG射精エフェクト2_0002.png":"img/pictures/Material0036.png", 
            "img/pictures/ECG射精エフェクト2_0003.png":"img/pictures/Material0037.png", 
            "img/pictures/ECG射精エフェクト2_0004.png":"img/pictures/Material0038.png", 
            "img/pictures/ECG射精エフェクト2_0005.png":"img/pictures/Material0039.png", 
            "img/pictures/HCCG　膣カットイン_0001.png":"img/pictures/Material0040.png", 
            "img/pictures/HCCG　膣カットイン_0002.png":"img/pictures/Material0041.png", 
            "img/pictures/HCCG　膣カットイン_0003.png":"img/pictures/Material0042.png", 
            "img/pictures/HCCG_触手膣_0001.png":"img/pictures/Material0043.png", 
            "img/pictures/HCCG_触手膣_0002.png":"img/pictures/Material0044.png", 
            "img/pictures/HCCG_触手膣_0003.png":"img/pictures/Material0045.png", 
            "img/pictures/HCCG_触手膣_0004.png":"img/pictures/Material0046.png", 
            "img/pictures/HCCG_触手膣_0005.png":"img/pictures/Material0047.png", 
            "img/pictures/HCCGカットインベース.png":"img/pictures/Material0048.png", 
            "img/pictures/HCCGしりもみアニメ_0001.png":"img/pictures/Material0049.png", 
            "img/pictures/HCCGしりもみアニメ_0002.png":"img/pictures/Material0050.png", 
            "img/pictures/HCCGしりもみアニメ_0003.png":"img/pictures/Material0051.png", 
            "img/pictures/HCCGベロベロアニメ_0001.png":"img/pictures/Material0052.png", 
            "img/pictures/HCCGベロベロアニメ_0002.png":"img/pictures/Material0053.png", 
            "img/pictures/HCCGベロベロアニメ_0003.png":"img/pictures/Material0054.png", 
            "img/pictures/HCCGベロベロアニメ_0004.png":"img/pictures/Material0055.png", 
            "img/pictures/HCCG胸アニメ_0001.png":"img/pictures/Material0056.png", 
            "img/pictures/HCCG胸アニメ_0002.png":"img/pictures/Material0057.png", 
            "img/pictures/HCCG胸アニメ_0003.png":"img/pictures/Material0058.png", 
            "img/pictures/HCCG胸カットイン_0001.png":"img/pictures/Material0059.png", 
            "img/pictures/HCCG胸カットイン_0002.png":"img/pictures/Material0060.png", 
            "img/pictures/HCCG胸感度.png":"img/pictures/Material0061.png", 
            "img/pictures/HCCG口カットイン_0001.png":"img/pictures/Material0062.png", 
            "img/pictures/HCCG口カットイン_0002.png":"img/pictures/Material0063.png", 
            "img/pictures/HCCG口ピストン_0001.png":"img/pictures/Material0064.png", 
            "img/pictures/HCCG口ピストン_0002.png":"img/pictures/Material0065.png", 
            "img/pictures/HCCG口ピストン_0003.png":"img/pictures/Material0066.png", 
            "img/pictures/HCCG口ピストン_0004.png":"img/pictures/Material0067.png", 
            "img/pictures/HCCG口ピストン_0005.png":"img/pictures/Material0068.png", 
            "img/pictures/HCCG口ピストン_0006.png":"img/pictures/Material0069.png", 
            "img/pictures/HCCG口ピストン_0007.png":"img/pictures/Material0070.png", 
            "img/pictures/HCCG口ピストン_0008.png":"img/pictures/Material0071.png", 
            "img/pictures/HCCG指マンアニメ_0002.png":"img/pictures/Material0072.png", 
            "img/pictures/HCCG手マンアニメ_0001.png":"img/pictures/Material0073.png", 
            "img/pictures/HCCG手マンアニメ_0002.png":"img/pictures/Material0074.png", 
            "img/pictures/HCCG手マンアニメ_0003.png":"img/pictures/Material0075.png", 
            "img/pictures/HCCG尻カットイン_0001.png":"img/pictures/Material0076.png", 
            "img/pictures/HCCG尻カットイン_0002.png":"img/pictures/Material0077.png", 
            "img/pictures/HCCG尻カットイン_0003.png":"img/pictures/Material0078.png", 
            "img/pictures/HCCG絶頂_0001.png":"img/pictures/Material0079.png", 
            "img/pictures/HCCG絶頂_0002.png":"img/pictures/Material0080.png", 
            "img/pictures/HCCG乳首攻め_0001.png":"img/pictures/Material0081.png", 
            "img/pictures/HCCG乳首攻め_0002.png":"img/pictures/Material0082.png", 
            "img/pictures/HCCG乳首攻め_0003.png":"img/pictures/Material0083.png", 
            "img/pictures/HCCG乳首攻め_0004.png":"img/pictures/Material0084.png", 
            "img/pictures/HCCG乳首攻め_0005.png":"img/pictures/Material0085.png", 
            "img/pictures/HCCG乳首攻め_0006.png":"img/pictures/Material0086.png", 
            "img/pictures/HCCG乳首攻め_0007.png":"img/pictures/Material0087.png", 
            "img/pictures/HCCG乳首攻め_0008.png":"img/pictures/Material0088.png", 
            "img/pictures/HCCG標準尻揉み.png":"img/pictures/Material0089.png", 
            "img/pictures/HCCG標準尻揉み喫茶店.png":"img/pictures/Material0090.png", 
            "img/pictures/HCCG膣カットイン_0001.png":"img/pictures/Material0091.png", 
            "img/pictures/HCCG膣カットイン_0002.png":"img/pictures/Material0092.png", 
            "img/pictures/HCCG膣カットイン_0003.png":"img/pictures/Material0093.png", 
            "img/pictures/HCG アルシー自慰_0001.png":"img/pictures/Material0094.png", 
            "img/pictures/HCG アルシー自慰_0002.png":"img/pictures/Material0095.png", 
            "img/pictures/HCG アルシー自慰_0003.png":"img/pictures/Material0096.png", 
            "img/pictures/HCG アルシー自慰_0004.png":"img/pictures/Material0097.png", 
            "img/pictures/HCG アルシー自慰2_0001.png":"img/pictures/Material0098.png", 
            "img/pictures/HCG アルシー自慰2_0002.png":"img/pictures/Material0099.png", 
            "img/pictures/HCG アルシー自慰2_0003.png":"img/pictures/Material0100.png", 
            "img/pictures/HCG アルシー自慰2_0004.png":"img/pictures/Material0101.png", 
            "img/pictures/HCG アルシー自慰2_0005.png":"img/pictures/Material0102.png", 
            "img/pictures/HCG アルシー自慰2_0006.png":"img/pictures/Material0103.png", 
            "img/pictures/HCG アルシー自慰2+_0001.png":"img/pictures/Material0104.png", 
            "img/pictures/HCG アルシー自慰2+_0002.png":"img/pictures/Material0105.png", 
            "img/pictures/HCG アルシー自慰2+_0003.png":"img/pictures/Material0106.png", 
            "img/pictures/HCG アルシー自慰2+_0004.png":"img/pictures/Material0107.png", 
            "img/pictures/HCGアルシー睡眠エロ_0001.png":"img/pictures/Material0108.png", 
            "img/pictures/HCGアルシー睡眠エロ_0002.png":"img/pictures/Material0109.png", 
            "img/pictures/HCGアルシー睡眠エロ_0003.png":"img/pictures/Material0110.png", 
            "img/pictures/HCGアルシー睡眠エロ_0004.png":"img/pictures/Material0111.png", 
            "img/pictures/HCGアルシー睡眠エロ_0005.png":"img/pictures/Material0112.png", 
            "img/pictures/HCGアルシー睡眠エロ_0006.png":"img/pictures/Material0113.png", 
            "img/pictures/HCGゴブリン敗北_0001.png":"img/pictures/Material0114.png", 
            "img/pictures/HCGゴブリン敗北_0002.png":"img/pictures/Material0115.png", 
            "img/pictures/HCGゴブリン敗北_0003.png":"img/pictures/Material0116.png", 
            "img/pictures/HCGゴブリン敗北_0004.png":"img/pictures/Material0117.png", 
            "img/pictures/HCGゴブリン敗北_0005.png":"img/pictures/Material0118.png", 
            "img/pictures/HCGゴブリン敗北_0006.png":"img/pictures/Material0119.png", 
            "img/pictures/HCGゴブリン敗北_0007.png":"img/pictures/Material0120.png", 
            "img/pictures/HCGゴブリン敗北_0008.png":"img/pictures/Material0121.png", 
            "img/pictures/HCGゴブリン敗北_0009.png":"img/pictures/Material0122.png", 
            "img/pictures/HCGゴブリン敗北_0010.png":"img/pictures/Material0123.png", 
            "img/pictures/HCGゴブリン敗北_0011.png":"img/pictures/Material0124.png", 
            "img/pictures/HCGゴブリン敗北_0012.png":"img/pictures/Material0125.png", 
            "img/pictures/HCGゴブリン敗北2_0001.png":"img/pictures/Material0126.png", 
            "img/pictures/HCGゴブリン敗北2_0002.png":"img/pictures/Material0127.png", 
            "img/pictures/HCGゴブリン敗北2_0003.png":"img/pictures/Material0128.png", 
            "img/pictures/HCGゴブリン敗北2_0004.png":"img/pictures/Material0129.png", 
            "img/pictures/HCGゴブリン敗北2_0005.png":"img/pictures/Material0130.png", 
            "img/pictures/HCGゴブリン敗北2_0006.png":"img/pictures/Material0131.png", 
            "img/pictures/HCGゴブリン敗北2_0007.png":"img/pictures/Material0132.png", 
            "img/pictures/HCGゴブリン敗北2_0008.png":"img/pictures/Material0133.png", 
            "img/pictures/HCGローパー敗北_0001.png":"img/pictures/Material0134.png", 
            "img/pictures/HCGローパー敗北_0002.png":"img/pictures/Material0135.png", 
            "img/pictures/HCGローパー敗北_0003.png":"img/pictures/Material0136.png", 
            "img/pictures/HCGローパー敗北_0004.png":"img/pictures/Material0137.png", 
            "img/pictures/HCGローパー敗北_0005.png":"img/pictures/Material0138.png", 
            "img/pictures/HCGローパー敗北_0006.png":"img/pictures/Material0139.png", 
            "img/pictures/HCGローパー敗北_0007.png":"img/pictures/Material0140.png", 
            "img/pictures/HCGローパー敗北_0008.png":"img/pictures/Material0141.png", 
            "img/pictures/HCGローパー敗北_0009.png":"img/pictures/Material0142.png", 
            "img/pictures/HCGローパー敗北_0010.png":"img/pictures/Material0143.png", 
            "img/pictures/HCGローパー敗北_0011.png":"img/pictures/Material0144.png", 
            "img/pictures/HCGローパー敗北_0012.png":"img/pictures/Material0145.png", 
            "img/pictures/HCGローパー敗北_0013.png":"img/pictures/Material0146.png", 
            "img/pictures/HCGローパー敗北2_0001.png":"img/pictures/Material0147.png", 
            "img/pictures/HCGローパー敗北2_0002.png":"img/pictures/Material0148.png", 
            "img/pictures/HCGローパー敗北2_0003.png":"img/pictures/Material0149.png", 
            "img/pictures/HCGローパー敗北2_0004.png":"img/pictures/Material0150.png", 
            "img/pictures/HCGローパー敗北2_0005.png":"img/pictures/Material0151.png", 
            "img/pictures/HCGローパー敗北2_0006.png":"img/pictures/Material0152.png", 
            "img/pictures/HCGローパー敗北2_0007.png":"img/pictures/Material0153.png", 
            "img/pictures/HCGローパー敗北2_0008.png":"img/pictures/Material0154.png", 
            "img/pictures/HCGローパー敗北2_0009.png":"img/pictures/Material0155.png", 
            "img/pictures/HCGローパー敗北2_0010.png":"img/pictures/Material0156.png", 
            "img/pictures/障気演出.png":"img/pictures/Material0157.png", 
            "img/pictures/真っ黒.png":"img/pictures/Material0158.png", 
            "img/pictures/真っ白.png":"img/pictures/Material0159.png", 
            "img/tilesets/A1_公園区.png":"img/tilesets/Material0160.png", 
            "img/tilesets/A1_中央区.png":"img/tilesets/Material0161.png", 
            "img/tilesets/A1_虹姫の部屋.png":"img/tilesets/Material0162.png", 
            "img/tilesets/A2_公園区.png":"img/tilesets/Material0163.png", 
            "img/tilesets/A2_中央区.png":"img/tilesets/Material0164.png", 
            "img/tilesets/A2_農業区.png":"img/tilesets/Material0165.png", 
            "img/tilesets/A5_遠景用.png":"img/tilesets/Material0166.png", 
            "img/tilesets/A5_公園区.png":"img/tilesets/Material0167.png", 
            "img/tilesets/A5_商店区.png":"img/tilesets/Material0168.png", 
            "img/tilesets/A5_中央区.png":"img/tilesets/Material0169.png", 
            "img/tilesets/B_ボス部屋.png":"img/tilesets/Material0170.png", 
            "img/tilesets/B_ボス部屋2.png":"img/tilesets/Material0171.png", 
            "img/tilesets/B_ミカゲとコウの家_1F.png":"img/tilesets/Material0172.png", 
            "img/tilesets/B_ミカゲとコウの家_B1.png":"img/tilesets/Material0173.png", 
            "img/tilesets/B_ラスボスの部屋.png":"img/tilesets/Material0174.png", 
            "img/tilesets/B_花園.png":"img/tilesets/Material0175.png", 
            "img/tilesets/B_喫茶店_内装.png":"img/tilesets/Material0176.png", 
            "img/tilesets/B_教会_外観.png":"img/tilesets/Material0177.png", 
            "img/tilesets/B_教会_内装.png":"img/tilesets/Material0178.png", 
            "img/tilesets/B_教会_内装_廃墟.png":"img/tilesets/Material0179.png", 
            "img/tilesets/B_公園区.png":"img/tilesets/Material0180.png", 
            "img/tilesets/B_司令室.png":"img/tilesets/Material0181.png", 
            "img/tilesets/B_住宅区.png":"img/tilesets/Material0182.png", 
            "img/tilesets/B_商店区.png":"img/tilesets/Material0183.png", 
            "img/tilesets/B_小部屋.png":"img/tilesets/Material0184.png", 
            "img/tilesets/B_小部屋2.png":"img/tilesets/Material0185.png", 
            "img/tilesets/B_人体実験室.png":"img/tilesets/Material0186.png", 
            "img/tilesets/B_草原.png":"img/tilesets/Material0187.png", 
            "img/tilesets/B_村長の家_1F.png":"img/tilesets/Material0188.png", 
            "img/tilesets/B_大部屋.png":"img/tilesets/Material0189.png", 
            "img/tilesets/B_大部屋2.png":"img/tilesets/Material0190.png", 
            "img/tilesets/B_地下闘技場.png":"img/tilesets/Material0191.png", 
            "img/tilesets/B_中央区.png":"img/tilesets/Material0192.png", 
            "img/tilesets/B_中部屋.png":"img/tilesets/Material0193.png", 
            "img/tilesets/B_中部屋2.png":"img/tilesets/Material0194.png", 
            "img/tilesets/B_通路.png":"img/tilesets/Material0195.png", 
            "img/tilesets/B_通路2.png":"img/tilesets/Material0196.png", 
            "img/tilesets/B_展望台_1.png":"img/tilesets/Material0197.png", 
            "img/tilesets/B_虹姫の部屋.png":"img/tilesets/Material0198.png", 
            "img/tilesets/B_農業区.png":"img/tilesets/Material0199.png", 
            "img/tilesets/B_民家_1F.png":"img/tilesets/Material0200.png", 
            "img/tilesets/C_ミカゲとコウの家_2F.png":"img/tilesets/Material0201.png", 
            "img/tilesets/C_ミカゲとコウの家_B1.png":"img/tilesets/Material0202.png", 
            "img/tilesets/C_ラスボスの部屋.png":"img/tilesets/Material0203.png", 
            "img/tilesets/C_花園.png":"img/tilesets/Material0204.png", 
            "img/tilesets/C_喫茶店_内装.png":"img/tilesets/Material0205.png", 
            "img/tilesets/C_公園区.png":"img/tilesets/Material0206.png", 
            "img/tilesets/C_住宅区.png":"img/tilesets/Material0207.png", 
            "img/tilesets/C_商店区.png":"img/tilesets/Material0208.png", 
            "img/tilesets/C_食べ物.png":"img/tilesets/Material0209.png", 
            "img/tilesets/C_人体実験室.png":"img/tilesets/Material0210.png", 
            "img/tilesets/C_草原.png":"img/tilesets/Material0211.png", 
            "img/tilesets/C_村.png":"img/tilesets/Material0212.png", 
            "img/tilesets/C_村長の家_2F.png":"img/tilesets/Material0213.png", 
            "img/tilesets/C_大部屋.png":"img/tilesets/Material0214.png", 
            "img/tilesets/C_大部屋2.png":"img/tilesets/Material0215.png", 
            "img/tilesets/C_地下闘技場.png":"img/tilesets/Material0216.png", 
            "img/tilesets/C_中央区.png":"img/tilesets/Material0217.png", 
            "img/tilesets/C_中部屋.png":"img/tilesets/Material0218.png", 
            "img/tilesets/C_中部屋2.png":"img/tilesets/Material0219.png", 
            "img/tilesets/C_展望台_2.png":"img/tilesets/Material0220.png", 
            "img/tilesets/C_民家_2F.png":"img/tilesets/Material0221.png", 
            "img/tilesets/D_花園.png":"img/tilesets/Material0222.png", 
            "img/tilesets/D_公園区.png":"img/tilesets/Material0223.png", 
            "img/tilesets/D_住宅区.png":"img/tilesets/Material0224.png", 
            "img/tilesets/D_草原.png":"img/tilesets/Material0225.png", 
            "img/tilesets/D_村.png":"img/tilesets/Material0226.png", 
            "img/tilesets/D_大部屋.png":"img/tilesets/Material0227.png", 
            "img/tilesets/D_大部屋2.png":"img/tilesets/Material0228.png", 
            "img/tilesets/D_中央区.png":"img/tilesets/Material0229.png", 
            "img/tilesets/D_中部屋.png":"img/tilesets/Material0230.png", 
            "img/tilesets/D_中部屋2.png":"img/tilesets/Material0231.png", 
            "img/tilesets/E_村.png":"img/tilesets/Material0232.png", 
            "img/tilesets/E_農業区.png":"img/tilesets/Material0233.png", 
            "img/tilesets/fsm_Forest01_A1_改変.png":"img/tilesets/Material0234.png", 
            "img/tilesets/fsm_Forest01_A2_改変.png":"img/tilesets/Material0235.png", 
            "img/tilesets/fsm_Forest01_A5_改変.png":"img/tilesets/Material0236.png", 
            "img/tilesets/fsm_Forest01_A5_繁華街.png":"img/tilesets/Material0237.png", 
            "img/tilesets/fsm_Forest01_B_改変.png":"img/tilesets/Material0238.png", 
            "img/tilesets/mori夜の大樹.png":"img/tilesets/Material0239.png", 
            "img/tilesets/SF_Inside_B加工.png":"img/tilesets/Material0240.png", 
            "img/tilesets/TileB_exterior4_改変.png":"img/tilesets/Material0241.png", 
            "img/tilesets/アナトールタイルC.png":"img/tilesets/Material0242.png", 
            "img/tilesets/ビーチ.png":"img/tilesets/Material0243.png", 
            "img/tilesets/ビーチセット.png":"img/tilesets/Material0244.png", 
            "img/tilesets/ビーチ砂.png":"img/tilesets/Material0245.png", 
            "img/tilesets/屋根窓改変.png":"img/tilesets/Material0246.png", 
            "img/tilesets/屋敷tile.png":"img/tilesets/Material0247.png", 
            "img/tilesets/屋敷屋根.png":"img/tilesets/Material0248.png", 
            "img/tilesets/屋敷建物.png":"img/tilesets/Material0249.png", 
            "img/tilesets/絵画.png":"img/tilesets/Material0250.png", 
            "img/tilesets/学校_A5.png":"img/tilesets/Material0251.png", 
            "img/tilesets/学校D.png":"img/tilesets/Material0252.png", 
            "img/tilesets/学校D+uroom.png":"img/tilesets/Material0253.png", 
            "img/tilesets/学校D+uroom+.png":"img/tilesets/Material0254.png", 
            "img/tilesets/学校inside.png":"img/tilesets/Material0255.png", 
            "img/tilesets/学校壁.png":"img/tilesets/Material0256.png", 
            "img/tilesets/教会2.png":"img/tilesets/Material0257.png", 
            "img/tilesets/教会床.png":"img/tilesets/Material0258.png", 
            "img/tilesets/教会壁.png":"img/tilesets/Material0259.png", 
            "img/tilesets/図書館床.png":"img/tilesets/Material0260.png", 
            "img/tilesets/図書館壁.png":"img/tilesets/Material0261.png", 
            "img/tilesets/図書館本.png":"img/tilesets/Material0262.png", 
            "img/tilesets/部屋床.png":"img/tilesets/Material0263.png", 
            "img/tilesets/部屋壁.png":"img/tilesets/Material0264.png", 
        }, 
        audio:{ 
            "audio/bgm/【BGM】04調教系「ruthless」（ややソフト、Future house）.ogg":"audio/bgm/Material0265.ogg",  
            "audio/bgm/【BGM】06純愛系「ワイルドローズ」（R&B風、大人っぽい感じ）.ogg":"audio/bgm/Material0266.ogg", 
            "audio/bgm/【BGM】09催眠系「hypnotism」（glitch系、シンセサイザー）.ogg":"audio/bgm/Material0267.ogg", 
            "audio/bgm/【BGM】険悪な雰囲気アウトボード.ogg":"audio/bgm/Material0268.ogg", 
            "audio/bgm/【BGM】陵辱系Hシーン【儀式っぽい感じ】.ogg":"audio/bgm/Material0269.ogg", 
            "audio/bgm/10暗く深い洞窟.ogg":"audio/bgm/Material0270.ogg", 
            "audio/bgm/11アヤしいなあ….ogg":"audio/bgm/Material0271.ogg", 
            "audio/bgm/12藍白.ogg":"audio/bgm/Material0272.ogg", 
            "audio/bgm/3わたしの帰る場所.ogg":"audio/bgm/Material0273.ogg", 
            "audio/bgm/4蒼色冒険記.ogg":"audio/bgm/Material0274.ogg", 
            "audio/bgm/5静寂を生む森.ogg":"audio/bgm/Material0275.ogg", 
            "audio/bgm/7お仕置き完了！.ogg":"audio/bgm/Material0276.ogg", 
            "audio/bgm/9水の都.ogg":"audio/bgm/Material0277.ogg", 
            "audio/bgm/ワインレッド.ogg":"audio/bgm/Material0278.ogg", 
            "audio/bgm/闇からの使者.ogg":"audio/bgm/Material0279.ogg", 
            "audio/bgm/雨のテーマ.ogg":"audio/bgm/Material0280.ogg", 
            "audio/bgm/幻想的な森.ogg":"audio/bgm/Material0281.ogg", 
            "audio/bgm/思考の牢.ogg":"audio/bgm/Material0282.ogg", 
            "audio/bgm/水色の陽炎.ogg":"audio/bgm/Material0283.ogg", 
            "audio/bgm/夜のチャイナタウン.ogg":"audio/bgm/Material0284.ogg", 
            "audio/bgm/予兆.ogg":"audio/bgm/Material0285.ogg", 
            "audio/bgs/PSE_学園モノ(日常)_足音校舎内ループ_TEMPO50.ogg":"audio/bgs/Material0286.ogg", 
            "audio/bgs/ピストンA反響ゆ.ogg":"audio/bgs/Material0287.ogg", 
            "audio/bgs/ピストンA反響速.ogg":"audio/bgs/Material0288.ogg", 
            "audio/bgs/ピストンタイプA（肉のぶつかる音入り）（ゆっくり）.ogg":"audio/bgs/Material0289.ogg", 
            "audio/bgs/ピストンタイプA（肉のぶつかる音入り）（速い）.ogg":"audio/bgs/Material0290.ogg", 
            "audio/bgs/ピストンタイプA（肉のぶつかる音入り）（中くらい）.ogg":"audio/bgs/Material0291.ogg", 
            "audio/bgs/ピストンタイプA（肉のぶつかる音入り）（非常にゆっくり）.ogg":"audio/bgs/Material0292.ogg", 
            "audio/se/【システムSE】カーソル移動音04.ogg":"audio/se/Material0293.ogg", 
            "audio/se/PSE_学園モノ(日常)_ぶつかる.ogg":"audio/se/Material0294.ogg", 
            "audio/se/PSE_学園モノ(日常)_起きる01.ogg":"audio/se/Material0295.ogg", 
            "audio/se/イベント音6.ogg":"audio/se/Material0296.ogg", 
            "audio/se/システム音21(1秒)s.ogg":"audio/se/Material0297.ogg", 
            "audio/se/パターン3_キャンセル音.ogg":"audio/se/Material0298.ogg", 
            "audio/se/パターン3_決定音.ogg":"audio/se/Material0299.ogg", 
            "audio/se/ピストンタイプA（肉のぶつかる音入り）１回.ogg":"audio/se/Material0300.ogg", 
            "audio/se/外出し①.ogg":"audio/se/Material0301.ogg", 
            "audio/se/挿入する時の音1.ogg":"audio/se/Material0302.ogg", 
            "audio/se/挿入する時の音2.ogg":"audio/se/Material0303.ogg", 
            "audio/se/挿入する時の音3（勢いよく一気に入れる）.ogg":"audio/se/Material0304.ogg", 
            "audio/se/大量ぶっかかけ.ogg":"audio/se/Material0305.ogg", 
            "audio/se/中出し④.ogg":"audio/se/Material0306.ogg", 
            "audio/se/濡れた膣を触る2.ogg":"audio/se/Material0307.ogg", 
        }, 
        movies:{ 
        } 
    }; 

    
    var _Bitmap_load = Bitmap.load;
    Bitmap.load = function(url) {
        var _url = decodeURIComponent(url);
        if (ReplaceNameList.img.hasOwnProperty(_url)) {
            url = ReplaceNameList.img[_url];
        }
        return _Bitmap_load.call(this, url);
    };
    
    var _Bitmap_request = Bitmap.request;
    Bitmap.request = function(url) {
        var _url = decodeURIComponent(url);
        if (ReplaceNameList.img.hasOwnProperty(_url)) {
            url = ReplaceNameList.img[_url];
        }
        return _Bitmap_request.call(this, url);
    };
    
    var _Html5Audio_setup = Html5Audio.setup;
    Html5Audio.setup = function (url) {
        var _url = decodeURIComponent(url);
        if (ReplaceNameList.audio.hasOwnProperty(_url)) {
            url = ReplaceNameList.audio[_url];
        }
        _Html5Audio_setup.call(this, url);
    };

    var _WebAudio_initialize = WebAudio.prototype.initialize;
    WebAudio.prototype.initialize = function(url) {
        var _url = decodeURIComponent(url);
        if (ReplaceNameList.audio.hasOwnProperty(_url)) {
            url = ReplaceNameList.audio[_url];
        }
        _WebAudio_initialize.call(this, url);
    };
    
    var _Graphics_playVideo = Graphics.playVideo;
    Graphics.playVideo = function(src) {
        if (ReplaceNameList.movies.hasOwnProperty(src)) {
            src = ReplaceNameList.movies[src];
        }
        _Graphics_playVideo.call(this, src);
    };
}());